language: "en"

pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_entity_featurizer_regex"
  - name: "ner_crf"
    features:
      [
        ["low", "title", "upper"],
        ["bias", "upper", "title", "digit", "pattern"],
        ["low", "title", "upper"],
      ]
