language: "en"

pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_featurizer_spacy"
  - name: "intent_entity_featurizer_regex"
  - name: "ner_crf"
    features:
      [
        ["pos", "pos2"],
        [
          "bias",
          "low",
          "prefix5",
          "prefix2",
          "suffix5",
          "suffix3",
          "suffix2",
          "upper",
          "title",
          "digit",
          "pattern",
          "pos",
          "pos2",
        ],
        ["pos", "pos2"],
      ]
    BILOU_flag: false
  - name: "intent_classifier_sklearn"
